name = "site-h2"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "dist/client"
entry-point = "."

[build]
command = "yarn && yarn build"

[build.upload]
dir = "dist/worker"
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./worker.mjs"
