name = "site-h2"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-06"

[site]
bucket = "dist/client"
entry-point = "."

[build]
command = "yarn && yarn build"

[build.upload]
dir = "dist/worker"
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./worker.server.mjs"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Counter"]
